version: '2.1'

networks:
  ethereum-net:
    driver: bridge

volumes:
  geth_data: {}

services:
  geth:
    image: ethereum/client-go:v1.10.13
    container_name: geth
    volumes:
      - geth_data:/root
    command:
      - '--ropsten'
      - '--syncmode=full'
      - '--gcmode=archive'
      - '--cache.preimages'
      - '--cache.trie.rejournal=48h'
      - '--maxpeers=200'
      - '--pcscdpath='
      - '--snapshot=false'
      - '--port=30303'
      - '--http'
      - '--http.addr=0.0.0.0'
      - '--http.port=8545'
      - '--http.vhosts=*'
      - '--http.corsdomain=*'
      - '--http.api=web3,eth,net,personal,miner,txpool,debug,admin'
      - '--ws'
      - '--ws.addr=0.0.0.0'
      - '--ws.port=8546'
      - '--ws.origins=*'
      - '--ws.api=web3,eth,net,personal,miner,txpool,debug,admin'
      - '--metrics'
      - '--metrics.expensive'
      - '--metrics.addr=0.0.0.0'
      - '--metrics.port=6080'
      - '--pprof'
      - '--pprof.addr=0.0.0.0'
      - '--pprof.port=6081'
      - '--txlookuplimit=0'
    restart: unless-stopped
    ports:
      - '8545:8545'
      - '8546:8546'
      - '6080:6080'
      - '6081:6081'
    networks:
      - ethereum-net
    labels:
      org.label-schema.group: 'ethereum-geth'
