networks:
  ethereum-net:
    driver: bridge

volumes:
  redis_data: {}
  postgres_data: {}

services:
  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - ethereum-net
    labels:
      org.label-schema.group: 'ethereum-geth'

  postgres:
    image: postgres:12.10-alpine
    container_name: postgres
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
    restart: unless-stopped
    ports:
      - '5432:5432'
    networks:
      - ethereum-net
    labels:
      org.label-schema.group: 'ethereum-geth'
