#!/usr/bin/env python3


import sys

if sys.version_info < (3, 9):
    raise EnvironmentError("Python 3.9 or above is required")

from blockchainetl.cli import cli

if __name__ == "__main__":
    sys.exit(cli())  # pylint: disable=E1120
