ORDERBOOK_COLUMNS = [
    "_st",
    "_st_day",
    "blknum",
    "txhash",
    "txpos",
    "xfer_logpos",
    "order_logpos",
    "token_type",
    "token_address",
    "token_id",
    "token_value",
    "from_address",
    "to_address",
    "maker",
    "taker",
    "price",
    "currency",
    "pack_index",
    "pack_count",
    "value",
    "value_from",
    "value_to",
    "platform",
    "app",
    "action",
    "pattern",
    "fee_from",
    "fee_to",
    "fee_currency",
    "fee_value",
]

TF_COLUMNS = [
    "_st",
    "blknum",
    "txhash",
    "txpos",
    "x_from_address",
    "x_to_address",
    "x_token_address",
    "x_token_id",
    "x_token_value",
    "xfer_logpos",
]

EF_COLUMNS = [
    "_st",
    "blknum",
    "s_from_address",
    "s_to_address",
    "s_token_address",
    "s_token_id",
    "s_token_value",
    "sfer_logpos",
    "txhash",
    "txpos",
]

TX_COLUMNS = ["_st", "blknum", "ether", "tx_to", "txhash", "txpos"]
